
apiVersion: v1
kind: Service
metadata:
  name: {{ template "xap-manager.fullname" . }}-hs
  labels:
    app: {{ template "xap-manager.name" . }}
    chart: {{ template "xap-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: zk-client
      port: {{ .Values.hs.ports.zkClient }}
    - name: zk-server
      port: {{ .Values.hs.ports.zkServer }}
    - name: zk-leader-election
      port: {{ .Values.hs.ports.zkLeaderElection }}
    - name: lookup-service
      port: {{ .Values.hs.ports.lookupService }}
  clusterIP: None
  selector:
    selectorId: {{ template "xap-manager.fullname" . }}
