
apiVersion: v1
kind: Service
metadata:
  name: {{ template "xap-manager.fullname" . }}-service
  labels:
    app: {{ template "xap-manager.name" . }}
    chart: {{ template "xap-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.ports.api.port }}
      {{if (.Values.service.ports.api.nodePort)}}
      nodePort: {{ .Values.service.ports.api.nodePort }}
      {{ end }}
  selector:
    selectorId: {{ template "xap-manager.fullname" . }}
